language: go

go:
    - 1.3
    - tip

before_install:
    - sudo add-apt-repository 'deb http://us.archive.ubuntu.com/ubuntu/ utopic main restricted universe multiverse'
    - sudo add-apt-repository 'deb http://us.archive.ubuntu.com/ubuntu/ utopic-updates main restricted universe multiverse'
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq libglew1.10 libglfw3 libglfw3-dev libglew-dev
