language: go

go:
    - 1.3
    - tip

before_install:
    - sudo add-apt-repository 'deb http://us.archive.ubuntu.com/ubuntu/ utopic universe multiverse'
    - sudo add-apt-repository 'deb http://us.archive.ubuntu.com/ubuntu/ utopic-updates universe multiverse'
    - sudo apt-get update -qy
    - sudo apt-get install -qy libglew1.10 libglfw3 libglfw3-dev libglew-dev
